sudo: required
dist: trusty

language: haxe

haxe:
  - "3.4.7"
  - "development"

matrix:
  allow_failures:
    - haxe: development

install:
  - yes | haxelib install all

script:
  - haxe build-js.hxml
  - haxe build-cpp.hxml
  - haxe build-cs.hxml
  - haxe build-java.hxml
  - haxe build-neko.hxml
  - haxe build-hl.hxml


deploy:
  - provider: script
    haxe: 3.4.7
    script: bash ./release_haxelib.sh $HAXELIB_PWD
    on:
      tags: true